<?php
/**
 * Filename: functions.php
 * Purpose: Holds all of the backend code required to implement this themes features
 * Author: Matthew Sigley, adapted from the functions.php in "Twenty Ten" by the WordPress team
 * Version: 1.20101014
 */
/** Tell WordPress to run constructionmates_mobile_setup() when the 'after_setup_theme' hook is run. */
add_action( 'after_setup_theme', 'constructionmates_mobile_setup' );
//Check if theme has already been loaded, since hooks are sometimes run twice
if ( ! function_exists( 'constructionmates_mobile_setup' ) ):
	/**
	 * Function Name: constructionmates_mobile_setup
	 * Purpose: Tells wordpress what features this theme supports.
	 */
	function constructionmates_mobile_setup() {
		// This theme styles the visual editor with editor-style.css to match the theme style.
		add_editor_style();
		// This theme uses post thumbnails
		add_theme_support( 'post-thumbnails' );
		add_image_size( 'homepage-post-thumb', 630, 9999 ); // Permalink thumbnail size for homepage
		// Add default posts and comments RSS feed links to head
		add_theme_support( 'automatic-feed-links' );
		// This theme uses wp_nav_menu() in one location.
		register_nav_menus( array(
			'primary' => __( 'Primary Navigation', 'constructionmates_mobile' ),
		) );
	}
endif;
/**
 * Get our wp_nav_menu() fallback, wp_page_menu(), to show a home link.
 *
 * To override this in a child theme, remove the filter and optionally add
 * your own function tied to the wp_page_menu_args filter hook.
 */
function constructionmates_mobile_page_menu_args( $args ) {
	$args['show_home'] = true;
	return $args;
}
add_filter( 'wp_page_menu_args', 'constructionmates_mobile_page_menu_args' );

/**
 * Makes some changes to the <title> tag, by filtering the output of wp_title().
 *
 * If we have a site description and we're viewing the home page or a blog posts
 * page (when using a static front page), then we will add the site description.
 *
 * If we're viewing a search result, then we're going to recreate the title entirely.
 * We're going to add page numbers to all titles as well, to the middle of a search
 * result title and the end of all other titles.
 *
 * The site title also gets added to all titles.
 *
 *
 * @param string $title Title generated by wp_title()
 * @param string $separator The separator passed to wp_title(). Twenty Ten uses a
 * 	vertical bar, "|", as a separator in header.php.
 * @return string The new title, ready for the <title> tag.
 */
function constructionmates_mobile_filter_wp_title( $title, $separator ) {
	// Don't affect wp_title() calls in feeds.
	if ( is_feed() )
		return $title;

	// The $paged global variable contains the page number of a listing of posts.
	// The $page global variable contains the page number of a single post that is paged.
	// We'll display whichever one applies, if we're not looking at the first page.
	global $paged, $page;

	if ( is_search() ) {
		// If we're a search, let's start over:
		$title = sprintf( __( 'Search results for %s', 'constructionmates_mobile' ), '"' . get_search_query() . '"' );
		// Add a page number if we're on page 2 or more:
		if ( $paged >= 2 )
			$title .= " $separator " . sprintf( __( 'Page %s', 'constructionmates_mobile' ), $paged );
		// Add the site name to the end:
		$title .= " $separator " . get_bloginfo( 'name', 'display' );
		// We're done. Let's send the new title back to wp_title():
		return $title;
	}

	// Otherwise, let's start by adding the site name to the end:
	$title .= get_bloginfo( 'name', 'display' );

	// If we have a site description and we're on the home/front page, add the description:
	$site_description = get_bloginfo( 'description', 'display' );
	if ( $site_description && ( is_home() || is_front_page() ) )
		$title .= " $separator " . $site_description;

	// Add a page number if necessary:
	if ( $paged >= 2 || $page >= 2 )
		$title .= " $separator " . sprintf( __( 'Page %s', 'constructionmates_mobile' ), max( $paged, $page ) );

	// Return the new title to wp_title():
	return $title;
}
add_filter( 'wp_title', 'constructionmates_mobile_filter_wp_title', 10, 2 );

/**
 * Sets the post excerpt length to 40 characters.
 *
 * To override this length in a child theme, remove the filter and add your own
 * function tied to the excerpt_length filter hook.
 *
 * @return int
 */
function constructionmates_mobile_excerpt_length( $length ) {
	return 40;
}
add_filter( 'excerpt_length', 'constructionmates_mobile_excerpt_length' );

/**
 * Returns a "Continue Reading" link for excerpts
 *
 * @return string "Continue Reading" link
 */
function constructionmates_mobile_continue_reading_link() {
	return '  <div class="read-more-job-btn"><span><a href="'. get_permalink() . '">' . __( 'Read More', 'constructionmates_mobile' ) . '</a></span> </div>';
}

/**
 * Replaces "[...]" (appended to automatically generated excerpts) with an ellipsis and constructionmates_mobile_continue_reading_link().
 *
 * To override this in a child theme, remove the filter and add your own
 * function tied to the excerpt_more filter hook.
 *
 * @return string An ellipsis
 */
function constructionmates_mobile_auto_excerpt_more( $more ) {
	return ' &hellip;' .constructionmates_mobile_continue_reading_link();
}
add_filter( 'excerpt_more', 'constructionmates_mobile_auto_excerpt_more' );

/**
 * Adds a pretty "Continue Reading" link to custom post excerpts.
 *
 * To override this link in a child theme, remove the filter and add your own
 * function tied to the get_the_excerpt filter hook.
 *
 * @return string Excerpt with a pretty "Continue Reading" link
 */
function constructionmates_mobile_custom_excerpt_more( $output ) {
	if ( has_excerpt() && ! is_attachment() ) {
		$output .= constructionmates_mobile_continue_reading_link();
	}
	return $output;
}
add_filter( 'get_the_excerpt', 'constructionmates_mobile_custom_excerpt_more' );
// Original PHP code by Chirp Internet: www.chirp.com.au // Please acknowledge use of this code by including this header. 
/**
 * Custom Truncate function for content boxes and other custom content areas
 *
 * @return string Truncated string under length $limit, cut off at $break, if it exists, with pad on the 
 *  end of it
 */
function myTruncate($string, $limit, $break=".", $pad="...") { 
	// return with no change if string is shorter than $limit 
	if(strlen($string) <= $limit) return $string; 
	
	// is $break present between $limit and the end of the string? 
	if(false !== ($breakpoint = strpos($string, $break, $limit))) { 
		if($breakpoint < strlen($string) - 1) { 
			$string = substr($string, 0, $breakpoint) . $pad; 
			} 
		} 
	return $string; 
	}

/**
 * Remove inline styles printed when the gallery shortcode is used.
 *
 * Galleries should be styled in the theme's style.css if they are going to be used in the design
 *
 * @return string The gallery style filter, with the styles themselves removed.
 */
function constructionmates_mobile_remove_gallery_css( $css ) {
	return preg_replace( "#<style type='text/css'>(.*?)</style>#s", '', $css );
}
add_filter( 'gallery_style', 'constructionmates_mobile_remove_gallery_css' );

if ( ! function_exists( 'constructionmates_mobile_comment' ) ) :
/**

 * Template for comments and pingbacks.
 
 * To override this walker in a child theme without modifying the comments template

 * simply create your own constructionmates_mobile_comment(), and that function will be used instead.

 *

 * Used as a callback by wp_list_comments() for displaying the comments.

 *

 */
function constructionmates_mobile_comment( $comment, $args, $depth ) {

	$GLOBALS['comment'] = $comment;

	switch ( $comment->comment_type ) :

		case 'pingback' :

		case 'trackback' :

	?>

	<li class="post pingback">

		<p><?php _e( 'Pingback:', 'constructionmates_mobile' ); ?> <?php comment_author_link(); ?><?php edit_comment_link( __( 'Edit', 'constructionmates_mobile' ), '<span class="edit-link">', '</span>' ); ?></p>

	<?php

			break;

		default :

	?>

	<li <?php comment_class(); ?> id="li-comment-<?php comment_ID(); ?>">

		<article id="comment-<?php comment_ID(); ?>" class="comment">

			<footer class="comment-meta">

				<div class="comment-author vcard">

					<?php

						$avatar_size = 68;

						if ( '0' != $comment->comment_parent )

							$avatar_size = 39;



						echo get_avatar( $comment, $avatar_size );



						/* translators: 1: comment author, 2: date and time */

						printf( __( '%1$s on %2$s <span class="says">said:</span>', 'constructionmates_mobile' ),

							sprintf( '<span class="fn">%s</span>', get_comment_author_link() ),

							sprintf( '<a href="%1$s"><time pubdate datetime="%2$s">%3$s</time></a>',

								esc_url( get_comment_link( $comment->comment_ID ) ),

								get_comment_time( 'c' ),

								/* translators: 1: date, 2: time */

								sprintf( __( '%1$s at %2$s', 'constructionmates_mobile' ), get_comment_date(), get_comment_time() )

							)

						);

					?>

					<?php edit_comment_link( __( 'Edit', 'constructionmates_mobile' ), '<span class="edit-link">', '</span>' ); ?>

				</div><!-- .comment-author .vcard -->



				<?php if ( $comment->comment_approved == '0' ) : ?>

					<em class="comment-awaiting-moderation"><?php _e( 'Your comment is awaiting moderation.', 'constructionmates_mobile' ); ?></em>

					<br />

				<?php endif; ?>

			</footer>
			
			<div class="comment-content"><?php comment_text(); ?></div>

			<div class="reply">

				<?php comment_reply_link( array_merge( $args, array( 'reply_text' => __( 'Reply <span>&darr;</span>', 'constructionmates_mobile' ), 'depth' => $depth, 'max_depth' => $args['max_depth'] ) ) ); ?>

			</div><!-- .reply -->

		</article><!-- #comment-## -->



	<?php

			break;

	endswitch;

}

endif; // ends check for twentyeleven_comment()

/**
 * Register widgetized areas, including two sidebars and four widget-ready columns in the footer.
 *
 * To override constructionmates_mobile_widgets_init() in a child theme, remove the action hook and add your own
 * function tied to the init hook.
 *
 * @uses register_sidebar
 */
function constructionmates_mobile_widgets_init() {
	
	// Area 1, located at header the social media.
	register_sidebar( array(
		'name' => __( 'Social Widget Area', 'constructionmates_mobile' ),
		'id' => 'social-widget-area',
		'description' => __( 'Social Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h2>',
		'after_title' => '</h2>',
	) );
	
	
	// Area 1, located Below of the slider.
	register_sidebar( array(
		'name' => __( 'Home Widget Area', 'constructionmates_mobile' ),
		'id' => 'home-widget-area',
		'description' => __( 'Home Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h1>',
		'after_title' => '</h1>',
	) );
	
	
	// Area 2, located Below of the slider.
	register_sidebar( array(
		'name' => __( 'Home1 Widget Area', 'constructionmates_mobile' ),
		'id' => 'home1-widget-area',
		'description' => __( 'Home1 Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h1>',
		'after_title' => '</h1>',
	) );
	
	
	// Area 3, located Below of the slider.
	register_sidebar( array(
		'name' => __( 'Home2 Widget Area', 'constructionmates_mobile' ),
		'id' => 'home2-widget-area',
		'description' => __( 'Home2 Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h1>',
		'after_title' => '</h1>',
	) );
	
	register_sidebar( array(
		'name' => __( 'Apply Widget Area', 'constructionmates_mobile' ),
		'id' => 'apply-widget-area',
		'description' => __( 'Apply Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '',
		'after_title' => '',
	) );
	
	
	
	register_sidebar( array(
		'name' => __( 'Testimonial_innerpage Widget Area', 'constructionmates_mobile' ),
		'id' => 'testimonial_innerpage-widget-area',
		'description' => __( 'Testimonial_innerpage Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '',
		'after_title' => '',
	) );
	
	register_sidebar( array(
		'name' => __( 'Highlights Widget Area', 'constructionmates_mobile' ),
		'id' => 'highlights-widget-area',
		'description' => __( 'Highlights Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '',
		'after_title' => '',
	) );
	
	register_sidebar( array(
		'name' => __( 'Home_Content Widget Area', 'constructionmates_mobile' ),
		'id' => 'home_content-widget-area',
		'description' => __( 'Home_Content Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '',
		'after_title' => '',
	) );
	
	// Area 1, located at the top social
	
	register_sidebar( array(
		'name' => __( 'Social Widget Area', 'constructionmates_mobile' ),
		'id' => 'social-widget-area',
		'description' => __( 'social Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h2>',
		'after_title' => '</h2>',
	) );
	
	// Area 1, located at the top Subscribe.
	register_sidebar( array(
		'name' => __( 'Subscribe Widget Area', 'constructionmates_mobile' ),
		'id' => 'subscribe-widget-area',
		'description' => __( 'subscribe Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h2>',
		'after_title' => '</h2>',
	) );
	
	register_sidebar( array(
		'name' => __( 'Footer Widget Area', 'constructionmates_mobile' ),
		'id' => 'footer-widget-area',
		'description' => __( 'footer Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h2>',
		'after_title' => '</h2>',
	) );
	
	register_sidebar( array(
		'name' => __( 'Slide Widget Area', 'constructionmates_mobile' ),
		'id' => 'slide-widget-area',
		'description' => __( 'Slide Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h2>',
		'after_title' => '</h2>',
	) );
	

	// Area 1, located at the top menu.
	register_sidebar( array(
		'name' => __( 'Header Right Widget Area', 'constructionmates_mobile' ),
		'id' => 'header-right-widget-area',
		'description' => __( 'Header Right Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '',
		'after_title' => '',
	) );
	
	register_sidebar( array(
		'name' => __( 'Paypal Widget Area', 'constructionmates_mobile' ),
		'id' => 'paypal-widget-area',
		'description' => __( 'Paypal Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h2>',
		'after_title' => '</h2>',
	) );
	
	register_sidebar( array(
		'name' => __( 'Calculator Widget Area', 'constructionmates_mobile' ),
		'id' => 'calculator-widget-area',
		'description' => __( 'Calculator Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h2>',
		'after_title' => '</h2>',
	) );
	
	// Area 1, located at the top menu.
	//register_sidebar( array(
	//	'name' => __( 'Top Menu Widget Area', 'constructionmates_mobile' ),
	//	'id' => 'top-menu-widget-area',
	//	'description' => __( 'Top Menu Widget Area', 'constructionmates_mobile' ),
	//	'before_widget' => '<li>',
	//	'after_widget' => '</li>',
	//	'before_title' => '',
	//	'after_title' => '',
	//) );


// Area 3, located in the left sidebar.
	//$logo_src = bloginfo('template_url').'/images/inner_icon.png';
	//echo get_template_directory_uri();
	register_sidebar( array(
		'name' => __( 'Sidebar Widget Area', 'constructionmates_mobile' ),
		'id' => 'sidebar-widget-area',
		'description' => __( 'The Sidebar Widget Area', 'constructionmates_mobile' ),
		'before_widget' => '',
		'after_widget' => '',
		'before_title' => '<h3>',
		'after_title' => '</h3>',
	) );
	
	// Area 2, located at the home page banner .
		//comment by sheruji 28jan 2013
	//register_sidebar( array(
	//	'name' => __( 'Home Page Banner Widget Area', 'constructionmates_mobile' ),
	//	'id' => 'home-page-banner-widget-area',
	//	'description' => __( 'The Home Page Banner Widget Area', 'constructionmates_mobile' ),
	//	'before_widget' => '',
	//	'after_widget' => '',
	//	'before_title' => '',
	//	'after_title' => '',
	//) );

	
	
	// Area 4, located at the bottom menu.
	//comment by sheruji 28jan 2013
	//register_sidebar( array(
	//	'name' => __( 'Bottom Menu Widget Area', 'constructionmates_mobile' ),
	//	'id' => 'bottom-menu-widget-area',
	//	'description' => __( 'Bottom Menu Widget Area', 'constructionmates_mobile' ),
	//	'before_widget' => '',
	//	'after_widget' => '',
	//	'before_title' => '',
	//	'after_title' => '',
	//) );

}
/** Register sidebars by running constructionmates_mobile_widgets_init() on the widgets_init hook. */
add_action( 'widgets_init', 'constructionmates_mobile_widgets_init' );

/**
 * Removes the default styles that are packaged with the Recent Comments widget.
 *
 * To override this in a child theme, remove the filter and optionally add your own
 * function tied to the widgets_init action hook.
 *
 */
function constructionmates_mobile_remove_recent_comments_style() {
	global $wp_widget_factory;
	remove_action( 'wp_head', array( $wp_widget_factory->widgets['WP_Widget_Recent_Comments'], 'recent_comments_style' ) );
}
add_action( 'widgets_init', 'constructionmates_mobile_remove_recent_comments_style' );

if ( ! function_exists( 'constructionmates_mobile_posted_on' ) ) :
/**
 * Prints HTML with meta information for the current post—date/time and author.
 *
 * @since Twenty Ten 1.0
 */
function constructionmates_mobile_posted_on() {
	printf( __( '<span class="%1$s">Posted on</span> %2$s <span class="meta-sep">by</span> %3$s', 'constructionmates_mobile' ),
		'meta-prep meta-prep-author',
		sprintf( '<a href="%1$s" title="%2$s" rel="bookmark"><span class="entry-date">%3$s</span></a>',
			get_permalink(),
			esc_attr( get_the_time() ),
			get_the_date()
		),
		sprintf( '<span class="author vcard"><a class="url fn n" href="%1$s" title="%2$s">%3$s</a></span>',
			get_author_posts_url( get_the_author_meta( 'ID' ) ),
			sprintf( esc_attr__( 'View all posts by %s', 'constructionmates_mobile' ), get_the_author() ),
			get_the_author()
		)
	);
}
endif;

if ( ! function_exists( 'constructionmates_mobile_posted_in' ) ) :
/**
 * Prints HTML with meta information for the current post (category, tags and permalink).
 *
 * @since Twenty Ten 1.0
 */
function constructionmates_mobile_posted_in() {
	// Retrieves tag list of current post, separated by commas.
	$tag_list = get_the_tag_list( '', ', ' );
	if ( $tag_list ) {
		$posted_in = __( 'This entry was posted in %1$s and tagged %2$s. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'constructionmates_mobile' );
	} elseif ( is_object_in_taxonomy( get_post_type(), 'category' ) ) {
		$posted_in = __( 'This entry was posted in %1$s. Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'constructionmates_mobile' );
	} else {
		$posted_in = __( 'Bookmark the <a href="%3$s" title="Permalink to %4$s" rel="bookmark">permalink</a>.', 'constructionmates_mobile' );
	}
	// Prints the string, replacing the placeholders.
	printf(
		$posted_in,
		get_the_category_list( ', ' ),
		$tag_list,
		get_permalink(),
		the_title_attribute( 'echo=0' )
	);
}
endif;

/**
 * Function Name: constructionmates_mobile_custom_rss2
 * Purpose: Outputs the rss2 feed template defined in the constructionmates_mobile theme folder
 */
function constructionmates_mobile_custom_rss2(){
	include TEMPLATEPATH . '/feed-rss2.php';
}

/**
 * Function Name: constructionmates_mobile_custom_rss2
 * Purpose: Outputs the rss2 feed template defined in the constructionmates_mobile theme folder
 */
function constructionmates_mobile_custom_rss(){
	include TEMPLATEPATH . '/feed-rss.php';
}

/**
 * Function Name: constructionmates_mobile_custom_rss_setup
 * Purpose: Overwrites the default rss 1.0 and rss 2.0 templates with the custom rss templates defined
 *  in the constructionmates_mobile theme folder, if they exist. If no custom rss templates are defined, the wordpress
 *  default templates will be used.
 */
function constructionmates_mobile_custom_rss_setup(){
	if(file_exists(TEMPLATEPATH . '/feed-rss2.php')){
		add_feed('rss', 'constructionmates_mobile_custom_rss');
		}
	if(file_exists(TEMPLATEPATH . '/feed-rss2.php')){
		add_feed('rss2', 'constructionmates_mobile_custom_rss2');
		}
}

add_action('init', 'constructionmates_mobile_custom_rss_setup');

//A unique id to be given to each slider for styling purposes and so that jquery can tell the sliders appart
$jquery_slider_unique_id = 1;


/**
 * Function Name: jquery_slider_1
 * Purpose: Creates a jquery slide based on the posts in the query string. This particular style of
 *  slider will have an image area at the top, with a text overlay on the bottom, and next/previous
 *  arrows for navigation.
 * Input:
 *  -query_string(string): A wordpress serialized query string for the posts you wish to populate the
 *   slider with. See the query_posts function for further documention on this.
 *  -width(decimal): The of the slider in pixels.
 *  -height(decimal): The height of the slider in pixels.
 *  -interval(integer): The time between slide changes in milliseconds.
 */
function jquery_slider_1($query_string, $width=630, $height=250, $interval=5000){
	global $jquery_slider_unique_id;
	
	//Container div for slider
	echo '<div class="slider-1-container" id="slider-id-'.$jquery_slider_unique_id.'" style="width: '.$width.'px; height: '.$height.'px;" >' . "\n" .
		'<ul>' . "\n";
		
	//Previous slide link
	?>
	<a class="prev-link">
		<span class="prev-text">&larr;</span>
	</a>
	<?php
	
	//Next slide link
	?>
	<a class="next-link">
		<span class="next-text">&rarr;</span>
	</a>
    <?php
	//Create an integer variable for assigning slide number classes to the list items
	$slide_number = 1;
	
	//Start a Seperate wordpress loop for the jquery slides using a new WP_Query object
	$my_query = new WP_Query($query_string);
	
	//var_dump($my_query);
	while ($my_query->have_posts()) : $my_query->the_post();
		//Get the custom fields for the post
		$custom_fields = get_post_custom($my_query->post->ID);
		if (has_post_thumbnail($my_query->post->ID) && array_key_exists('slider title', $custom_fields) && array_key_exists('slider description', $custom_fields) ){
			$post_thumb_id = get_post_thumbnail_id($my_query->post->ID);
			$post_thumb = wp_get_attachment_image_src($post_thumb_id, 'homepage-post-thumb', false);
			?>
			<li class="slide slide-number-<?php echo $slide_number; ?>" style="background: url('<?php echo $post_thumb[0]; ?>') bottom left no-repeat #8B8B8B; width: <?php echo $width; ?>px; height: <?php echo $height; ?>px;" >
            	<div class="slide-container-div" style="width: <?php echo $width; ?>px; height: <?php echo $height; ?>px;">
                    <div class="text-container">
                        <span class="title"><?php echo $custom_fields['slider title'][0]; ?></span>
                        <p class="description"><?php echo $custom_fields['slider description'][0]; ?></p>
                    </div>
                    <a class="read-more-link" href="<?php echo get_permalink($my_query->post->ID); ?>" >
                        <span class="read-more-text">Read More &raquo;</span>
                    </a>
                </div>
            
            <!--Image tag for preloading the slide's image-->
            <img src="<?php echo $post_thumb[0]; ?>" style="background: url:('<?php echo $post_thumb[0]; ?>'); display: none;" />
            
            </li>
            
    		<?php
			
			//A slide was created for the slider, so increment the slide_number
			$slide_number++;
			}
			endwhile;
	echo '</ul>' . "\n" .
		'</div><!--.slider_1_container-->';
	
	//JQuery to run this slider
	echo '<script type="text/javascript" src="'.get_bloginfo('template_url').'/js/slider1.js.php?id='.$jquery_slider_unique_id.'&amp;last_slide='.($slide_number-1).'&amp;interval='.$interval.'&amp;width='.$width.'"></script>' . "\n";
	
	//Increment the unique identifier for the sliders, so the next slider has a unique id
	$jquery_slider_unique_id++;
}

function jquery_slider_1_head(){
	echo '<!--CSS for JQuery Slider 1-->';
	echo "\n" . '<link rel="stylesheet" href="'.get_bloginfo('template_url').'/css/slider1.css" type="text/css" media="all" />' . "\n";
}

//Add the stylesheet for slider_1 to the <head>
add_action('wp_head', 'jquery_slider_1_head');

/**
 * Function Name: jquery_slider_2
 * Purpose: Creates a jquery slide based on the posts in the query string. This particular style of
 *  slider will have an image area at the top, with a text overlay on the bottom, and next/previous
 *  arrows for navigation.
 * Input:
 *  -query_string(string): A wordpress serialized query string for the posts you wish to populate the
 *   slider with. See the query_posts function for further documention on this.
 *  -width(decimal): The of the slider in pixels.
 *  -height(decimal): The height of the slider in pixels.
 *  -interval(integer): The time between slide changes in milliseconds.
 */
function jquery_slider_2($query_string, $width=630, $height=250, $interval=5000){
	global $jquery_slider_unique_id;
	
	//Container div for slider
	echo '<div class="slider-2-container" id="slider-id-'.$jquery_slider_unique_id.'" style="width: '.$width.'px; height: '.$height.'px;" >' . "\n" .
		'<ul>' . "\n";
	
	//Create an integer variable for assigning slide number classes to the list items
	$slide_number = 1;
	
	//Start a Seperate wordpress loop for the jquery slides using a new WP_Query object
	$my_query = new WP_Query($query_string);
	
	while ($my_query->have_posts()) : $my_query->the_post();
		//Get the custom fields for the post
		$custom_fields = get_post_custom($my_query->post->ID);
		if (has_post_thumbnail($my_query->post->ID) && array_key_exists('slider title', $custom_fields) ){
			$post_thumb_id = get_post_thumbnail_id($my_query->post->ID);
			$post_thumb = wp_get_attachment_image_src($post_thumb_id, 'homepage-post-thumb', false);
			?>
			<li class="slide slide-number-<?php echo $slide_number; ?>" style="background: url('<?php echo $post_thumb[0]; ?>') top left no-repeat #8B8B8B; width: <?php echo $width; ?>px; height: <?php echo $height; ?>px;" >
            	<div class="slide-container-div" style="width: <?php echo $width; ?>px; height: <?php echo $height; ?>px;">
                    <div class="text-container" style="width: <?php echo $width; ?>px; height: 30%;" >
                        <span class="title"><?php echo $custom_fields['slider title'][0]; ?></span>
                        <p class="description"><?php echo $custom_fields['slider description'][0]; ?></p>
                        <a class="read-more-link" href="<?php echo get_permalink($my_query->post->ID); ?>" >
                            <span class="read-more-text">Read More</span>
                        </a>
                    </div>
                </div>
                        
            <!--Image tag for preloading the slide's image-->
            <img src="<?php echo $post_thumb[0]; ?>" style="background: url:('<?php echo $post_thumb[0]; ?>'); display: none;" />
            
            </li>

    		<?php
			
			//A slide was created for the slider, so increment the slide_number
			$slide_number++;
			}
			endwhile;
	echo '</ul>' . "\n";
	
	//Start a for loop for the creation of the number links
	echo '<ul class="number-list">' . "\n";
	for($i=1; $i<$slide_number; $i++){
		?>
        <li class="number-item">
        	<a class="number-link link-number-<?php echo $i; ?>"><span class="number-text"><?php echo $i; ?></span></a>
        </li>
        <?php
		}
	echo '</ul>' . "\n";
	echo '</div><!--.slider_2_container-->';

	//JQuery to run this slider
	echo '<script type="text/javascript" src="'.get_bloginfo('template_url').'/js/slider2.js.php?id='.$jquery_slider_unique_id.'&amp;last_slide='.($slide_number-1).'&amp;interval='.$interval.'&amp;width='.$width.'"></script>' . "\n";
	
	//Increment the unique identifier for the sliders, so the next slider has a unique id
	$jquery_slider_unique_id++;
}

function jquery_slider_2_head(){
	echo '<!--CSS for JQuery Slider 2-->';
	echo "\n" . '<link rel="stylesheet" href="'.get_bloginfo('template_url').'/css/slider2.css" type="text/css" media="all" />' . "\n";
}

//Add the stylesheet for slider_2 to the <head>
add_action('wp_head', 'jquery_slider_2_head');


//////////////////////////////////// FOR HOME PAGE SLIDE SHOW NBN //////////////////////////////////////////////////////
if ( ! isset( $content_width ) )
	$content_width = 584;



/**
 * Register our sidebars and widgetized areas. Also register the default Epherma widget.
 *
 * @since Twenty Eleven 1.0
 */


/********************* nbn 15 Sept Start **********************/

function Get_Cat_Post($cat_ID)

{

/*$args = array(
    'numberposts' => 1,
    'offset' => 0,
     'category' =>$cat_ID,
     'child_of'   => 1,
     'orderby' => 'post_date',
    'order' => 'DESC',
    'post_type' => 'post',
    'post_status' => 'publish',
    'suppress_filters' => true );*/
query_posts( 'cat='.$cat_ID );
// The Loop

$i=1;

while ( have_posts() ) : the_post();

$image = wp_get_attachment_image_src( get_post_thumbnail_id( get_the_ID() ), 'single-post-thumbnail' );
	//echo '<a href="'.get_permalink(get_the_ID()).'">';
	if($i%3!=0)

	{

	echo '<div class="box_text_inner curs" onclick=\'javascript:redir("'.get_permalink(get_the_ID()).'");\'>';

	}

	else

	{

	echo '<div class="box_text_inner box_text_last curs" onclick=\'javascript:redir("'.get_permalink(get_the_ID()).'");\'>';	

	} 

	echo '<h2>';

	the_title();

	echo '</h2><div class="box_text_in"><div  class="text_middl_p">';

	echo '<p class="img_p">';

	//print_r($image);

	echo '<img src="'.$image[0].'">';

	echo '</p>';

	echo '<p class="text_middl_p">';

	echo $my_excerpt = get_excerpt_by_id(get_the_ID());

	//the_excerpt();

	

	echo '</p></div>';

	echo '<p class="more"><a href="'.get_permalink(get_the_ID()).'"><span>Read More &gt;</span></a></p>';

	echo '</div>';

	//echo get_the_ID();die;

	$image = wp_get_attachment_image_src( get_post_thumbnail_id( get_the_ID() ), 'single-post-thumbnail' );

	echo '</div>';

	$i++;

endwhile;

  ?> 

 <script>function redir(val){window.location = val;}</script> 
<?php 
// Reset Query
wp_reset_query();
}

function get_excerpt_by_id($post_id){
$the_post = get_post($post_id); //Gets post ID
$the_excerpt = $the_post->post_content; //Gets post_content to be used as a basis for the excerpt
$excerpt_length =25; //Sets excerpt length by word count
$the_excerpt = strip_tags(strip_shortcodes($the_excerpt)); //Strips tags and images
$words = explode(' ', $the_excerpt, $excerpt_length + 1);
if(count($words) > $excerpt_length) :
array_pop($words);
array_push($words, '…');
$the_excerpt = implode(' ', $words);
endif;
//$the_excerpt = '<p>' . $the_excerpt . '</p>';
return $the_excerpt;
}
function Get_Latest_Post()
{
$args = array(
    'numberposts' => 1,
    'offset' => 0,
     'category__not_in' =>array(10,12),
     'orderby' => 'post_date',
    'order' => 'DESC',
    'post_type' => 'post',
    'post_status' => 'publish',
    'suppress_filters' => true );
   $recentPost=wp_get_recent_posts( $args );
   $date=date('F j,Y',strtotime($recentPost[0]["post_date"]));
//echo "<PRE>";
//print_r($recentPost);
//echo "</PRE>";
 // echo $recentPost[0]["ID"];
  $my_excerpt = get_excerpt_by_id($recentPost[0]["ID"]);
        echo '<div class="box_text curs" onclick=\'javascript:redir("'.get_permalink($recentPost[0]["ID"]).'");\'>'; 
	echo '<h2>Blog Updates</h2>'; 
	echo '<div class="box_text_in">';
	echo  '<div class="text_middl_p">';
	echo '<div class="md_lov" style="min-height:69px;">'.$recentPost[0]["post_title"].'<br>';
	echo '<span>'.$date.'</span>';
	echo '</div>';
	echo '<p class="middle_p">';
	echo   $my_excerpt ;
	echo '</p>';
	echo '</div>';
	echo '<p class="more"><a href="'.get_permalink($recentPost[0]["ID"]).'"><span>Read More &gt;</span></a></p>';
	echo '</div></div>';
    ?> 
 <script>function redir(val){window.location = val;}</script> 
<?php 
}
add_action('init', 'init_theme_method');
 
function init_theme_method() {
   add_thickbox();
}

// hook failed login
add_action('wp_login_failed', 'my_front_end_login_fail'); 
 
function my_front_end_login_fail($username){
    // Get the reffering page, where did the post submission come from?
    $referrer = $_SERVER['HTTP_REFERER'];
 
    // if there's a valid referrer, and it's not the default log-in screen
    if(!empty($referrer) && !strstr($referrer,'wp-login') && !strstr($referrer,'wp-admin')){
        // let's append some information (login=failed) to the URL for the theme to use
        wp_redirect($referrer . '?login=failed');
	
    exit;
    }  
    
}
//4 June Dynamic Footer Banner Code Using NextGen Gallery Start here
function footer_banner_images()
{
			global $wpdb;
			$gid=1;
			$sql="select wp_ngg_gallery.name, wp_ngg_pictures.filename ,wp_ngg_gallery.path,wp_ngg_pictures.alttext,wp_ngg_pictures.description
			      from wp_ngg_gallery, wp_ngg_pictures
			      where wp_ngg_pictures.galleryid = wp_ngg_gallery.gid
			      and wp_ngg_gallery.gid =". $gid . " limit 0,4";
			$gallery=$wpdb->get_results($sql);
			return $gallery;			
				
}
//NextGen Gallery end here
/************ Function for showing right sidebar called at right_sidebar.php******************/
function Show_sidebar_right(){ ?>
	
		  <?php query_posts( array ( 'category_name' => 'construction_news_sidebar', 'posts_per_page' => 5,'orderby=date') ); ?>
      		 <?php while (have_posts()) : the_post(); ?>
                  <div class="trader-box">
		  <div class="traders-img_txt">
			<div class="traders-img_small">
				 <?php if(get_the_post_thumbnail( get_the_ID())==""){ ?>
				<img border="0" align="left" src="<?php bloginfo('template_url')?>/images/img_cate.png" />
				<?php } else {
				echo get_the_post_thumbnail( get_the_ID());
				}?>
			</div>
                       <div class="traders-head-txt"><span><a style="color:#707070;" href="<?php echo site_url().'?page_id=140&id=section'.get_the_ID();?>"><?php the_title(); ?></a></span></div>
		 </div>
		</div>
		  <?php endwhile;?>
     
          
<?php }
/************ Function for News content called at right_sidebar.php******************/
/************ Function for showing right sidebar called at right_sidebar.php******************/
function Show_sidebar_right_joinnow(){ ?>
			<?php /*Showing builder and treader detail right side bar*/
			if( get_the_ID()==710 || get_the_ID()==702){?>
			<div class="traders-head" style="color:#000;">Other Traders Near you</div>
			<?php
			global $wpdb;
			 $current_user = wp_get_current_user();
			$uid  = $current_user->ID;
			$userdata = $wpdb->get_results("select * FROM ".$wpdb->prefix."userlatlong where userid=".$uid);
			//print_r($userdata);
			$distance = 400;
			$lat = $userdata[0]->lat;
			$lng = $userdata[0]->lng;
			$tbl_name = $wpdb->prefix.'userlatlong';
			$tbl_name2 = $wpdb->prefix.'usermeta';
			$t_id = $_GET['id'];
			$query = "SELECT distinct a.*, ((ACOS(SIN($lat * 3.143 / 180) * SIN(a.`lat` * 3.143 / 180) + COS($lat * 3.143 / 180) * COS(a.`lat` * 3.143 / 180) * COS(($lng -a.`lng`) * 3.143 / 180)) * 180 / 3.143) * 60 * 1.1515) AS distance FROM `$tbl_name` as a, $tbl_name2 as b where a.userid = b.user_id HAVING userid !=$uid and userid !=$t_id and lng !='' and usertype=2 ORDER BY distance ASC limit 0,3";
			$retrieve_data = $wpdb->get_results($query);
			foreach ($retrieve_data as $retrieved_data){
			$id= $retrieved_data->userid;
			$all_meta_for_user = get_user_meta($id);
			$myStr= $all_meta_for_user['about_company'][0];
			$company=substr($myStr, 0, 50);
			preg_match("/src='(.*?)'/i",get_avatar($id,150), $matches);
			$a=explode('=',$matches[0]);
			$a1=explode("'",$a[1]);
			?>
		   <div class="trader-box">
                  <div class="traders-img_txt">
                <div class="traders-img_small"><a href="<?php echo site_url();?>?page_id=710&id=<?php echo $id;?>" style="color:#000;"><img border="0" align="left" src="<?php echo $a1[1];?>" /></a></div>
                <div class="traders-head-txt" style="color:#000;"><a href="<?php echo site_url();?>?page_id=710&id=<?php echo $id;?>" style="color:#000;"><?php echo $all_meta_for_user['first_name'][0];?></a><span><?php echo $company;?></span></div>
              </div>
                </div>
		<?php }?>
		<div class="more-traders"><span><a href="<?php echo site_url();?>?page_id=13">More Traders</a></span></div>
		 <?php }
		 /*for builder listing,trader listing and job listing pages right sidebar*/
		 else if( get_the_ID()==11 || get_the_ID()==13 || get_the_ID()==15){?>
			<div class="traders-head" style="color:#000;">Future Jobs</div>
			<?php global $wpdb;
			$retrieve_data = $wpdb->get_results("SELECT * FROM wp_jobpost where  published='1' ORDER BY id desc limit 0,5");
			foreach ($retrieve_data as $retrieved_data){
			$job_detail=$retrieved_data->job_detail;
			$cont=substr($job_detail, 0, 50);
			 preg_match("/src='(.*?)'/i",get_avatar($retrieved_data->user_id,150), $matches);
			  //echo $matches[0];
			  $a=explode('=',$matches[0]);
			  $a1=explode("'",$a[1]);
		         $image_name=(explode("/",$a1[1]));
			
			$image=$retrieved_data->file_name;
			if(!$retrieved_data->file_name)
			{
			$image = "jobslogo.png";
			}

			?>
		   <div class="trader-box">
                  <div class="traders-img_txt">
                <div class="traders-img_small"><a href="<?php echo site_url();?>?page_id=509&job=<?php echo $retrieved_data->id; ?>"><img border="0" align="left" src="<?php echo $a1[1];?>" style="width:40px;height:43px"/></a></div>
                <div class="traders-head-txt" style="color:#000;"><a href="<?php echo site_url();?>?page_id=509&job=<?php echo $retrieved_data->id;?>" style="color:#000;"><?php echo $retrieved_data->job_type;?></a><span><?php echo $cont;?></span></div>
              </div>
                </div>
		<?php } ?>
		<div class="more-traders"><span><a href="<?php echo site_url();?>?page_id=15">More Jobs</a></span> </div>
		 <?php }
		 /*for builder job listing*/
		 else if( get_the_ID()==1044){?>
			<div class="traders-head" style="color:#000;">Jobs</div>
			<?php global $wpdb;
			$retrieve_data = $wpdb->get_results("SELECT * FROM wp_jobpost where published='1' ORDER BY id desc limit 0,3");
			foreach ($retrieve_data as $retrieved_data){
			$job_detail=$retrieved_data->job_detail;
			$cont=substr($job_detail, 0, 50);
			 preg_match("/src='(.*?)'/i",get_avatar($retrieved_data->user_id,150), $matches);
			  //echo $matches[0];
			  $a=explode('=',$matches[0]);
			  $a1=explode("'",$a[1]);
		         $image_name=(explode("/",$a1[1]));
			
			$image=$retrieved_data->file_name;
			if(!$retrieved_data->file_name)
			{
			$image = "jobslogo.png";
			}
			?>
		   <div class="trader-box">
                  <div class="traders-img_txt">
                <div class="traders-img_small"><a href="<?php echo site_url();?>?page_id=509&job=<?php echo $retrieved_data->id;?>" style="color:#000;"><img border="0" align="left" src="<?php echo $a1[1];?>" style="width:40px;height:43px;"/></div>
                <div class="traders-head-txt" style="color:#000;"><span><a href="<?php echo site_url();?>?page_id=509&job=<?php echo $retrieved_data->id;?>" style="color:#000;"><?php echo $retrieved_data->job_type;?></a><?php echo $cont;?></span></div>
              </div>
                </div>
		<?php } ?>
		<div class="more-traders"><span><a href="<?php echo site_url();?>?page_id=15">More Jobs</a></span> </div>
		 <?php }
		 /*For Job Detail right side bar*/
		
		 /*For post a job right side bar*/
		 else if( get_the_ID()==354){?>
				<div class="traders-head" style="color:#000;">Builders</div>
				<?php
			global $wpdb;
			$retrieve_data = $wpdb->get_results("SELECT * FROM wp_usermeta where meta_key='usertype' and meta_value='3' ORDER BY user_id desc limit 0,3");
			foreach ($retrieve_data as $retrieved_data){
			$id= $retrieved_data->user_id;
			$all_meta_for_user = get_user_meta($id);
			$myStr= $all_meta_for_user['about_company'][0];
			$company=substr($myStr, 0, 50);
			preg_match("/src='(.*?)'/i",get_avatar($id,150), $matches);
			$a=explode('=',$matches[0]);
			$a1=explode("'",$a[1]);
			?>
		  		   <div class="trader-box">
                  <div class="traders-img_txt">
                <div class="traders-img_small"><a href="<?php echo site_url();?>?page_id=710&id=<?php echo $id;?>" style="color:#000;"><img border="0" align="left" src="<?php echo $a1[1];?>" /></a></div>
                <div class="traders-head-txt" style="color:#000;"><a href="<?php echo site_url();?>?page_id=702&id=<?php echo $id;?>" style="color:#000;"><?php echo $all_meta_for_user['first_name'][0];?></a><span><?php echo $company;?></span></div>
              </div>
                </div>
		<?php } ?>
		<div class="more-traders"><span><a href="<?php echo site_url();?>?page_id=11">More Builders</a></span> </div>
		 <?php }
		 /*Showing benefits right side bar*/
		else {?>
		<div class="traders-head" style="color:#000;">Benefits</div>
		 <?php query_posts( array ( 'category_name' => 'Benefits', 'posts_per_page' => 5,'orderby=date') ); ?>
      		 <?php while (have_posts()) : the_post(); ?>
                  <div class="trader-box">
		  <div class="traders-img_txt">
			<div class="traders-img_small">
				 <?php if(get_the_post_thumbnail( get_the_ID())==""){ ?>
				<img border="0" align="left" src="<?php bloginfo('template_url')?>/images/img_cate.png" />
				<?php } else {
				echo get_the_post_thumbnail( get_the_ID());
				}?>
			</div>
                       <div class="traders-head-txt"><span><a style="color:#707070;" href="<?php echo site_url().'?page_id=196&id=section'.get_the_ID();?>"><?php the_title(); ?></a></span></div>
		 </div>
		</div>
		  <?php endwhile;?>
		 
<?php   }}
/************ Function for News content called at right_sidebar.php******************/
function Show_News_content_mobile(){ ?>
 <h3>News</h3>
		<?php query_posts( array ( 'category_name' => 'News', 'posts_per_page' => -1 ) ); ?>
      			<?php while (have_posts()) : the_post(); ?>
			   <div class="tabs_search"> 
			<ul class="tab_2list">
			   <li>
			      <?php if(get_the_post_thumbnail( get_the_ID())==""){ ?>
			       <div class="span2 new_imgbox"><img src="<?php bloginfo('template_url')?>/images/logo-img-demo.png" alt=""></div>
			    <?php }else{ ?>
                  <div class="span2 new_imgbox"><?php echo get_the_post_thumbnail( get_the_ID());?></div> <?php } ?>
				<h3 class="new_headingh"><?php the_title(); ?></h3>
				<span class="top_s"><?php the_excerpt();?>
				 </span>
				<div class="clear-both"></div></li></ul></div>
		       <?php endwhile;
}

/************ Function for News content called at right_sidebar.php at faq page******************/
function Show_FaqNews_content(){ ?>
 <h3>News</h3>
		<?php query_posts( array ( 'category_name' => 'News', 'posts_per_page' => 1 ) ); ?>
      			<?php while (have_posts()) : the_post(); ?>
			   <div class="job-list-part">
			      <?php if(get_the_post_thumbnail( get_the_ID())==""){ ?>
			       <div class="job-img-part"><img src="<?php bloginfo('template_url')?>/images/logo-img-demo.png" alt=""></div>
			    <?php }else{ ?>
                  <div class="job-img-part"><?php echo get_the_post_thumbnail( get_the_ID());?></div> <?php } ?>
				<div class="job-list-txt-plc">
				<h5><?php the_title(); ?></h5>
				<?php the_excerpt();?>
				 </div>
			         </div>	
		       <?php endwhile;
}

/************ Function for News content of sidebar called at page.php******************/
function Show_News_content_sidebar($id){ ?>
	<?php $sectionid=$_GET['id'];
	//echo $id;?>
	<script type="text/javascript">
	var id='<?php echo $sectionid;?>'; 
	$(document).ready(function() {
		//alert(id);
		document.location.href='#'+id;
	//$('#'+id).focus();
		});
</script>
	  <?php if($id==140){query_posts( array ( 'category_name' => 'construction_news_sidebar', 'posts_per_page' => -1) );}
	  elseif($id==196){query_posts( array ( 'category_name' => 'Benefits', 'posts_per_page' => -1));} ?>
      		 <?php while (have_posts()) : the_post(); ?>
			 <div class="job-list-part" id="<?php echo 'section'.get_the_ID();?>">
			      <?php if(get_the_post_thumbnail( get_the_ID())==""){ ?>
			       <div class="job-img-part"><img src="<?php bloginfo('template_url')?>/images/logo-img-demo.png" alt=""></div>
			    <?php }else{ ?>
                  <div class="job-img-part"><?php echo get_the_post_thumbnail( get_the_ID());?></div> <?php } ?>
				<div class="job-list-txt-plc">
				<h5><?php the_title(); ?></h5>
				<?php the_content();?>
				 </div>
			         </div>	
		       <?php endwhile;
}
/*********** Advice section **************** called at rightsidebar */

function advice_section_dispaly(){
	  query_posts( array ( 'category_name' => 'Tips and Advice', 'posts_per_page' => 1) ); ?>
      		<?php while (have_posts()) : the_post();?>
			<div class="job-list-part">
				<?php if(get_the_post_thumbnail( get_the_ID())==""){ ?>
					<div class="job-img-part"><img src="<?php bloginfo('template_url')?>/images/logo-img-demo.png" alt=""></div>
				<?php }else{ ?>
					<div class="job-img-part"><?php echo get_the_post_thumbnail( get_the_ID());?></div>
				<?php } ?>
				<div class="job-list-txt-plc">
					<h5><?php the_title(); ?></h5>
					<?php the_excerpt();?>
				 </div>
			</div>	
		<?php endwhile;
}

function Show_question(){ ?>
 <h3>Question</h3>
		<?php query_posts( array ( 'category_name' => 'Question', 'posts_per_page' => 1 ) ); ?>
      			<?php while (have_posts()) : the_post(); ?>
			   <div class="job-list-part">
			      <?php if(get_the_post_thumbnail( get_the_ID())==""){ ?>
			      <!-- <div class="job-img-part"><img src="<?php //bloginfo('template_url')?>/images/logo-img-demo.png" alt=""></div>-->
			    <?php }else{ ?>
                  <div class="job-img-part"><?php echo get_the_post_thumbnail( get_the_ID());?></div> <?php } ?>
				<div class="job-list-txt-plc">
				<h5><?php the_title(); ?></h5>
				<?php the_excerpt();?>
				 </div>
			         </div>	
		       <?php endwhile;
}
function show_blog_content_mobile(){ ?>
		<?php query_posts( array ( 'category_name' => 'blog', 'posts_per_page' => -1 ) ); ?>
      			<?php while (have_posts()) : the_post(); ?>
			   <li><div class="more_btn"><a href="<?php echo site_url();?>?p=<?php echo get_the_ID();?>&info=1"><img src="<?php echo get_template_directory_uri(); ?>/images/more.png" alt="more"></a></div>
			      <?php if(get_the_post_thumbnail( get_the_ID())==""){ ?>
			      <!-- <div class="job-img-part"><img src="<?php //bloginfo('template_url')?>/images/logo-img-demo.png" alt=""></div>-->
			    <?php }else{ ?>
			 <div class="span2 new_imgbox"><?php echo get_the_post_thumbnail( get_the_ID());?></div> <?php } ?>
				<h3 class="new_headingh"><?php the_title(); ?></h3>
				<span class="top_s"><?php $excerpt = get_the_content();
					$excerpt = strip_shortcodes($excerpt);
					$excerpt = strip_tags($excerpt);
					$the_str = substr($excerpt, 0, 120);
					echo $the_str;?></span>
				<div class="clear-both"></div></li>
<?php endwhile;				 echo '<div class="slider">'.do_shortcode( "[featslider]" ).'</div>';
}
function show_popular_builder(){ ?>

		<h1 class="traders">Popular Builder</h1>
					<?php
	      global $wpdb;
	      $table_name2 = "wp_builders_hits";
	      //$querylimit="LIMIT 2";
	      $KOFTdrafts = $wpdb->get_results("SELECT * FROM $table_name2  ORDER BY hit DESC");  //print_r($KOFTdrafts); die('test');
 	      $c=0;
	      foreach($KOFTdrafts as $value)
	       {
		  $c=$c+1; 
		   $userid = $value->user_id;
		 $retrieve_data = $wpdb->get_results("SELECT * FROM wp_usermeta where meta_key='usertype' and meta_value='3' and user_id = $userid");?>
	     
	        <ul class="tab_2list">
	 <?php     foreach ($retrieve_data as $retrieved_data){
		
		  $id= $retrieved_data->user_id;
		  $all_meta_for_user = get_user_meta($id);
                  preg_match("/src='(.*?)'/i",get_avatar($id,150), $matches);
		  $a=explode('=',$matches[0]);
		  $a1=explode("'",$a[1]);
	 if($c==1)
	     {
	      ?>
	      <li class="clearfix">
              <a href="<?php echo site_url();?>?page_id=702&id=<?php echo $id;?>" ><img border="0" align="left" src="<?php echo $a1[1];?>" alt="" style="height:57px;width:57px;"></a>
                  <div class="span2"><h3><a href="<?php echo site_url();?>?page_id=702&id=<?php echo $id;?>&theme=handheld"><?php echo $all_meta_for_user['first_name'][0];echo "&nbsp";echo $all_meta_for_user['last_name'][0];?></a></h3><span class="top_s"><?php echo substr($all_meta_for_user['about_company'][0] ,0, 50);?></span></div>
            </li>
          <?php }
	 elseif($c==2)
	   { ?>   <li class="clearfix">
                  <a href="<?php echo site_url();?>?page_id=702&id=<?php echo $id;?>"><img border="0" align="left" src="<?php echo $a1[1];?>" alt="" style="height:57px;width:57px;"></a>
                 <div class="span2"><h3><a href="<?php echo site_url();?>?page_id=702&id=<?php echo $id;?>&theme=handheld"><?php echo $all_meta_for_user['first_name'][0];echo "&nbsp";echo $all_meta_for_user['last_name'][0];?></a></h3><span class="top_s"><?php echo substr($all_meta_for_user['about_company'][0] ,0, 50);?></span></div>
            </li>

            <div class="more_bilders"><span><a href="<?php echo site_url(); ?>?page_id=11&theme=handheld">More Builders</a></span></div>

	  <?php }
   }  }

}
		//--------------------//

//Show recent traders
function show_recent_trader_mobile(){ ?>
		<h1 class="traders new_content_heading">Recent Traders</h1>
		<ul class="tab_2list">
	    <?php
	    global $wpdb;
	    $retrieve_data = $wpdb->get_results("SELECT * FROM wp_usermeta where meta_key='usertype' and meta_value='2' ORDER BY user_id desc limit 0,2");
	    $counter=0;
	    foreach ($retrieve_data as $retrieved_data){
	    $counter++;
	    $id= $retrieved_data->user_id;
	    $all_meta_for_user = get_user_meta($id);
	    //$myStr= $all_meta_for_user['about_company'][0];
	    //$company=substr($myStr, 0, 50);
	    preg_match("/src='(.*?)'/i",get_avatar($id,150), $matches);
	    $a=explode('=',$matches[0]);
	    $a1=explode("'",$a[1]);
	    if($counter==1)
	    {
	    ?>
	      <li class="clearfix">
              <a href="<?php echo site_url();?>?page_id=710&id=<?php echo $id;?>" ><img border="0" align="left" src="<?php echo $a1[1];?>" alt="" style="height:50px;width:57px;"></a>
                  <div class="span2"><h3><a class="new_headText" href="<?php echo site_url();?>?page_id=702&id=<?php echo $id;?>&theme=handheld"><?php echo $all_meta_for_user['first_name'][0];echo "&nbsp";echo $all_meta_for_user['last_name'][0];?></a></h3><span class="top_s"><?php echo substr($all_meta_for_user['about_company'][0] ,0, 50);?></span></div>
            </li>
          <?php }
	 elseif($counter==2){
	   ?>   <li class="clearfix">
                  <a href="<?php echo site_url();?>?page_id=702&id=<?php echo $id;?>"><img border="0" align="left" src="<?php echo $a1[1];?>" alt="" style="height:50px;width:57px;"></a>
                 <div class="span2"><h3><a class="new_headText" href="<?php echo site_url();?>?page_id=710&id=<?php echo $id;?>&theme=handheld"><?php echo $all_meta_for_user['first_name'][0];echo "&nbsp";echo $all_meta_for_user['last_name'][0];?></a></h3><span class="top_s"><?php echo substr($all_meta_for_user['about_company'][0] ,0, 50);?></span></div>
            </li>
            <div class="more_bilders"><span><a href="<?php echo site_url();?>?page_id=13&theme=handheld">More Traders</a></span></div>
	<?php
	  }
	}
}
			//---------------------//
//show latest job			
		function show_latest_job_mobile(){ ?>
		<h1 class="traders new_content_heading"">Latest Jobs</h1>
	      	      <?php
			global $wpdb;
			$retrieve_data = $wpdb->get_results("SELECT id,job_category,count(job_category) as noj FROM wp_jobpost where published='1' GROUP BY job_category ORDER BY id desc limit 0,10");
			$j=0;?>
		<ul class="tab_2list showlstjobs">
		<?php foreach ($retrieve_data as $retrieved_data){
		  $j=$j+1; ?>
	      <li class="clearfix">
                  <div class="span2"><h3><a href="<?php echo site_url();?>?page_id=1188&job_cat=<?php echo $retrieved_data->job_category; ?>&theme=handheld"><?php echo $retrieved_data->job_category;?><span>(<?php echo $j_id=$retrieved_data->noj;?>)</span></a></h3></div>
            </li>
	  <?php 
   }  ?> <div class="more_bilders"><span><a href="<?php echo site_url();?>?page_id=15&theme=handheld">More Jobs</a></span></div>
   <?php }
		//--------------------//
		
		//show trades			
		function show_trades_mobile(){
		include_once(ABSPATH.'wp-content/plugins/job-post/pagination.class.php');
			?>
			<script type="text/javascript">
	 $(document).ready(function(){
	  pageid=1721;
		 $(".page_class").click(function(){
		 // alert(this.title);
		  owntitle = this.title;
		  $("#searchform").attr('action','http://constructionmates.co.uk/?page_id='+pageid+'&paging='+owntitle+'&theme=handheld');
		  $("#searchform").submit();
		  });
		 
		 //for next button
		 $('.next').click(function(){
		    owntitle = this.title;
		    $("#searchform").attr('action','http://constructionmates.co.uk/?page_id='+pageid+'&paging='+owntitle+'&theme=handheld');
		    $("#searchform").submit();
		    
		    });
		 
		 $('.prev').click(function(){
		    owntitle = this.title;
		    $("#searchform").attr('action','http://constructionmates.co.uk/?page_id='+pageid+'&paging='+owntitle+'&theme=handheld');
		    $("#searchform").submit();
		    
		    });
		 
		  });
</script>
		<h1 class="traders new_content_heading"">Categories for Trades</h1>
	      	      <?php
			global $wpdb;
//		  $query="SELECT * FROM wp_trades_categories ORDER BY category_name ASC";
//	 //echo $query;
//	 $retrieve_data = $wpdb->get_results($query);
//
//	 $items = count($retrieve_data); // number of total rows in the database
//	  if($items > 0) {
//        $p = new pagination;
//        $p->items($items);
//        $p->limit(10); // Limit entries per page
//        $p->target(site_url()."?page_id=1721&theme=handheld");
//        $p->currentPage($_GET[$p->paging]); // Gets and validates the current page
//        $p->calculate(); // Calculates what to show
//        $p->parameterName('paging');
//        $p->adjacents(1); //No. of page away from the current page
//        if(!isset($_GET['paging'])) {
//	    $p->page = 0;
//            $p->page = 1;
//	  }
//	 else
//	  {
//            $p->page = $_GET['paging'];
//	  }
//        //Query for limit paging
//        $limit = "LIMIT " . ($p->page - 1) * $p->limit  . ", " . $p->limit;
//    
//	  }
		 $retrieve_data = $wpdb->get_results("SELECT * FROM wp_trades_categories ORDER BY category_name ASC ");
?>
		<form name="searchform" id="searchform" method="post">
		<ul class="tab_2list showlstjobs">
		<?php foreach( $retrieve_data as $event_vals){
			$couter++; ?>
	      <li class="clearfix">
                  <div class="span2"><h3><a href="<?php echo site_url();?>?page_id=1722&catid=<?php echo $event_vals->id; ?>&theme=handheld"><?php echo $event_vals->category_name;?></a></h3></div>
            </li>
		</form>
 <?php }
		}?>
    <?php /*if($items > 0) {  $show = $p->show();}
    else
	  {
		$show = "No Record Found";
	  }
		*/  ?>

 <?php //Show  trades Detail
function show_trades_detail_mobile(){?>
		<h1 class="traders new_content_heading">Trades Users</h1>
		<ul class="tab_2list ">
	    <?php
	     global $wpdb;
	     $catid=$_REQUEST['catid'];
	     echo $data = $wpdb->get_var("SELECT category_name FROM wp_trades_categories where id='$catid'");
	     //$retrieve_data_value = $wpdb->get_results("SELECT * FROM wp_usermeta where meta_key='trades_name'");
	     $retrieve_data = $wpdb->get_results("SELECT * FROM wp_usermeta where meta_key='trades_name'");
	    //$counter=0;
	    foreach ($retrieve_data as $retrieved_data){
	    //$counter++;
	    $id= $retrieved_data->user_id;
	    $all_meta_for_user = get_user_meta($id);
	    $t=$all_meta_for_user['trades_name'][0];
	    $tt=explode(',',$t);
	    foreach($tt as $tt1)
	    {
		if($tt1==$data)
		{
			$all_meta_for_user = get_user_meta($id);
			//die("aaaaaaa");
			preg_match("/src='(.*?)'/i",get_avatar($id,150), $matches);
			$a=explode('=',$matches[0]);
			$a1=explode("'",$a[1]);
			$myStr= $all_meta_for_user['about_company'][0];
			$company=substr($myStr, 0, 150);
	    ?>
	      <li class="clearfix">
	      <div class="more_btn"><a href="<?php echo site_url();?>?page_id=710&id=<?php echo $id; ?>&theme=handheld"><img src="<?php echo get_template_directory_uri(); ?>/images/more.png" alt="more"></a></div>
               <img class="img_profile" src="<?php echo $a1[1];?>" >
		<div class="span2"> <h3><?php echo $all_meta_for_user['first_name'][0];echo "&nbsp";echo $all_meta_for_user['last_name'][0];?></h3>
		<span class="top_s"><?php echo $company;?></span>
		</div>
		</li>
            <!--<div class="more_bilders"><span><a href="<?php echo site_url();?>?page_id=13">More Traders</a></span></div>-->
		<?php  } } } ?>
		</ul>
	<?php }
	//*** End Trades Detail ***//
		
function show_job_conent_in_right(){ ?>
<div class="traders-head" style="color:#000;">Job Tools</div>
		   <div class="trader-box">
			<div class="traders-img_txt">
                    <div class="traders-head-txt" style="color:#000;"><span><a href="javascript:void(0);" onClick="printpage();" style="color: #707070;">PRINT THIS JOB</a></span></div>
                  </div>
                </div>
		 <div class="trader-box">
                   <div class="traders-img_txt">
			<?php
			$job_id=$_REQUEST['job'];
			global $wpdb;
			$retrieve_data = $wpdb->get_results("SELECT * FROM wp_jobpost where id='$job_id' and published='1'");
		        foreach ($retrieve_data as $retrieved_data){
		        $retrieved_data->job_type;
		        $Jt =  $retrieved_data->job_type;
		        $Jd = $retrieved_data->job_detail;
		        $Jl = $retrieved_data->job_location;
		        $Fn = $retrieved_data->file_name;
		        $Jty = $retrieved_data->job_type;
		        $Cn = $retrieved_data->contact;
		        $Pd = $retrieved_data->post_date;
}?>
                    <div class="traders-head-txt" style="color:#000;"><span><a href="pdf.php?Jt=<?php echo $Jt;?>&Fn=<?php echo $Fn ;?>&Jl=<?php echo $Jl;?>&Jd=<?php echo $Jd;?>&Cn=<?php echo $Cn;?>&Jty=<?php echo $Jty;?>&Pd=<?php echo $Pd;?>" id="download_link" style="color: #707070;">DOWNLOAD THIS JOB IN PDF</a></span></div>
                  </div>
                </div>
		<div class="trader-box">
                      <div class="traders-img_txt">
                    <div class="traders-head-txt" style="color:#000;"><span><a id="img_of_job" href="javascript:void(0)" style="color: #707070;"> View IMAGES FOR THIS JOB</a></span></div>
                  </div>
                    </div>

<?php } ?>
<?php function Show_faq_answer_mobile(){?>
				<script>
				function choose_change(cat){
				//alert(cat);
				//url="constructionmates.co.uk"
				window.location.href = '?page_id=20&cat='+cat;
				}
				</script>
				<script>
			      $(function() {
			      $( ".accordion" ).accordion();
			      });
			      </script>
			<p class="arc_h">FAQ</p>
			<?php
			global $wpdb;
			$catid=$_REQUEST['cat'];
			if($catid==""){
				 $Data = $wpdb->get_results("SELECT * FROM `wp_faq_category` LIMIT 0 , 1");
				 $catid= $Data[0]->id;
				}?>
			 <div class="csc_btn_box">
			<select class="target_select" onchange="choose_change(this.value)">
			<option>-Please Select-</option>
			<?php 
				$table_name2 = "wp_faq_category";
				//$querylimit="LIMIT 2";
				$retrieveData = $wpdb->get_results("SELECT * FROM $table_name2");
				foreach($retrieveData as $retrieveDatas){?>
				<option value="<?php echo $retrieveDatas->id;?>"><?php echo $retrieveDatas->category_name;?></option><!--<a href="<?php //echo site_url();?>?page_id=20&cat=<?php //echo $retrieveDatas->id;?>" ><?php //echo $retrieveDatas->category_name;?></a>-->
				<?php } ?>
				<div class="clear-both"></div>
			      </select>
			    </div>
			    <div id="<?php echo $retrieveDatas->id;?>">
			    <?php
			    $retrieve_category = $wpdb->get_results("select * from wp_faq_category where id= $catid ");
			    ?>
			      <h1 class="new_heading"><?php echo $retrieve_category[0]->category_name;?></h1>
				    <div class="accordion" >
				     <?php
					     $retrieve_value = $wpdb->get_results("select * from wp_faq_content where category= $catid ");
					     foreach($retrieve_value as $retrieve_value){?>
				      <h3><?php echo $retrieve_value->question;?></h3>
				      <div>
					<p><?php echo $retrieve_value->answer;?></p>
				      </div>
				      <?php }?>
				      </div>
				    </div>
				    </div>
<?php }
add_filter( 'show_admin_bar', 'hide_admin_bar_from_front_end');
function hide_admin_bar_from_front_end(){
  if (is_blog_admin()) {
    return true;
  }
  return false;
}

function home_page_slider(){
		global $current_user;
		global $wpdb;$user=$current_user->data->user_login;
 if(($current_user->usertype==1)or($current_user->usertype==4)){
		$redirect_to=site_url().'?page_id=487';
           
	  }else{
	       $redirect_to=site_url().'?page_id=442';
	  }
	    $retrieve_data1 = $wpdb->get_results("SELECT * from wp_users where `user_login`='$user'");
	//print_r($retrieve_data1);
	    $id1=$retrieve_data1[0]->ID;
	    $email=$retrieve_data1[0]->user_email; 
	    $all_meta_for_user = get_user_meta( $id1 );
	  //  print_r($all_meta_for_user);
	    // print_r($all_meta_for_user['trades_name'][0]);
	  $user_type=$all_meta_for_user['usertype'][0];?>
	  <div class="builder">
		 <div><span><a href="<?php echo site_url();?>?page_id=1465" class="active_arrow">Home</a></span></div>
		   <div>
			 <span>
			   <a href="<?php if($user_type ==2){ echo site_url().'?page_id=15'; }else {  echo site_url().'?page_id=1044'; }?>">Jobs</a>
			 </span>
		  </div>
               <?php if($user_type!=2){?> <div> <span><a href="<?php if(($user_type ==4)|| ($user_type ==3)){ echo site_url().'?page_id=1364'; }else {  echo site_url().'?page_id=354'; }?>">Post A Job</a></span></div><?php } ?>
              <div><span><a href="<?php echo site_url();?>?page_id=437&page=rwpm_frontend_inbox">Messages</a></span></div>
              <div><span> <a href="<?php echo $redirect_to; ?>">My Account</a></span>
	      </div>
	      <!--<span> <a href="<?php/* if($user_type==1 || $user_type==4){echo site_url().'?page_id=487&usertype='.$user_type; }elseif($user_type==2 || $user_type==3){echo site_url().'?page_id=442&usertype='.$user_type; }*/?>">My Account</a></span>-->
	     </div>
	     <!--Slider start-->
		  <div class="mainWrapper clearfix">
<!--topImg S-->
	<div class="topImg clearfix">
    <!--<img src="images/add.png" />-->
     <?php if(function_exists( 'wp_bannerize' ))
       wp_bannerize( 'group=mobile_home_image1&random=1&limit=1' );
?>
    </div>
<!--topImg E-->
	<div class="BottomBox clearfix">
    <!--Bottom_Left S-->
    	<div class="Bottom_Left">
        	<div class="topImg">
           <!-- <img src="images/add.png" />-->
            <?php
       if(function_exists( 'wp_bannerize' ))
       wp_bannerize( 'group=mobile_home_image2&random=1&limit=1' );
?>
    		</div>
            
            <div class="imgBox_Left FL">
          <!--  <img src="images/add.png" />-->
           <?php if(function_exists( 'wp_bannerize' ))
       wp_bannerize( 'group=mobile_home_image3&random=1&limit=1' );
?>
            </div>
            <div class="imgBox_right FR">
            <!--<img src="images/add.png" />-->
             <?php if(function_exists( 'wp_bannerize' ))
       wp_bannerize( 'group=mobile_home_image4&random=1&limit=1' );
?>
            </div>
            <div class="topImg clearfix">
           <!-- <img src="images/add.png" />-->
            <?php if(function_exists( 'wp_bannerize' ))
       wp_bannerize( 'group=mobile_home_image5&random=1&limit=1' );
?>
</div>
</div>
    <!--Bottom_Left E-->
    
    <div class="Bottom_right">
    <!--<img src="images/add.png" />-->
     <?php if(function_exists( 'wp_bannerize' ))
       wp_bannerize( 'group=mobile_home_image6&random=1&limit=1' );
?>
    </div>
    </div>
</div>   
<?php }?>