<?php
    define(TEMPLATE_PATH,ABSPATH.'wp-content/plugins/join-network/template');
    define(CLASSES_PATH,ABSPATH.'wp-content/plugins/join-network/classes');
       define(AVTARPLUGIN_PATH,ABSPATH.'wp-content/plugins/simple-local-avatars');
    //define(ADMIN_MODEL,ABSPATH.'wp-content/plugins/cis-questionary/admin/models/');
    //define(ADMIN_VIEWS,ABSPATH.'wp-content/plugins/cis-questionary/admin/views/');
    //define(ADMIN_HELPERS,ABSPATH.'wp-content/plugins/cis-questionary/admin/helper/');
    //define(ADMIN_MAIN,ABSPATH.'wp-content/plugins/cis-questionary/admin/');
    //define(SITE_PATH,site_url());    
?>
