<?php
/**
 *  MoPublication plugin for WordPress
 *  http://www.mopublication.com
 *
 *  Custom Help tab
 *
 *  (c) 2012 Grenade Technologies, South Africa
 *  http://www.grenadeco.com
 */

function mopub_admin_add_help_tab ()
{
    global $mopub_settings_page_id, $mopub_help_tab_content, $pluginName, $pluginDirectory, $faqLink, $contactLink;
    $screen = get_current_screen();

    if ( $screen->id != $mopub_settings_page_id ) return;

    //for WP 3.2 compatibility
    if ( ! method_exists($screen, 'add_help_tab') ) return;



    $screen->add_help_tab( array(
        'id' => 'using-mopub',                  //unique id for the tab
        'title' => __('Using '.$pluginName),   //unique visible title for the tab
        'content' => "<div class='help'><p><h5 class='big'>Using ".$pluginName."</h5></p>
<p>We've done our best to make the process of configuring your app as simple and straightforward as possible.</p>

<p>Refer to the tooltip next to each field (use your mouse to hover over the
<img src='" . plugins_url('/'.$pluginDirectory.'/images/question.png') . "' height='16' width='16' alt='?' /> icon) for a more detailed
explanation of what everything does. You can also get help for each step by cycling through the tabs to the left.</p>

<p>If you experience any problems that aren't addressed here, please browse our
<a href='".$faqLink."' target='_blank'>FAQs</a> or
<a href='".$contactLink."' target='_blank'>Contact us</a>. We'll be happy to assist you.</p>

<p>Enjoy your new app!</p>
</div>",
    ) );


    $screen->add_help_tab( array(
        'id' => 'using-mopub-customize',                  //unique id for the tab
        'title' => __('1. Customize'),   //unique visible title for the tab
        'content' => "<div class='help'><p><h5 class='big'>1. Customize</h5></p>

<p>This tab contains the general settings for your app such as the app name, description, colors, logos, and fonts.
Make sure you complete all the fields on this tab as they're mandatory.</p>

<p><b>Uploading images:</b> Click on the 'Upload Image' button and select the 'From Computer' tab to upload an image
from your computer. You will find the uploaded image in the 'Media Library' tab once it has been successfully uploaded.
Finally, make sure that the 'Full Size' option is selected, and click on the 'Insert into Post' button to use an
uploaded image.</p>

<p><b>Tip:</b> Click on the 'Save Changes' button regularly (top right) to ensure that all your changes are saved
correctly.</p></div>",
    ) );


    $screen->add_help_tab( array(
        'id' => 'using-mopub-content',                  //unique id for the tab
        'title' => __('2. Content Management'),   //unique visible title for the tab
        'content' => "<div class='help'><p><h5 class='big'>2. Content Management</h5></p>

<p>This tab contains settings for managing which content gets published to your app from WordPress.</p>

<p><b>Category menu:</b> Select which categories you want to show in your app's top menu
(the one just below your logo).</p>

<p><b>Pages:</b> Selected pages appear as icons along the menu bar at the bottom of your app.</p>

<p><b>Tip:</b> For best results, you should include 'Mobile Featured Images' as well as Mobile Video and Audio in
your posts. Make use of the custom fields generated by ".$pluginName." when editing or creating new
posts/articles.</p></div>",
    ) );


    $screen->add_help_tab( array(
        'id' => 'using-mopub-3',                  //unique id for the tab
        'title' => __('3. Third-Party Integration'),   //unique visible title for the tab
        'content' => "<div class='help'><p><h5 class='big'>3. Third-Party Integration</h5></p>

<p>This tab contains optional settings for configuring third-party services.</p>

<p><b>Statistics:</b> You can choose to use Google Analytics for tracking usage of your app. You must have a Google
Analytics account and fill in your Web Property ID (also known as a UA Number).</p>

<p><b>Note:</b> If you don't enter a valid Web Property ID you will not have access to any stats on app usage.</p>

<p><b>Social Sharing:</b>  Sharing is enabled by default in ".$pluginName.". This option allows you to either completely disable sharing, or you
can enter your own account details for a third-party service called
<a href='http://www.addthis.com' target='_blank'>AddThis</a> if you would like access to stats on
what your users are sharing.</p>

<p><b>Ad Management:</b> This option allows you to configure advertising settings for monetizing your app. The simplest
advertising option is a Custom Ad where you can upload images that will be embedded in your app. This option is great
for things like sponsorships where you expect the advert to be displayed for a long period of time and you don’t need to
track impressions/clicks, but the downside is that you will need to pay an app resubmission fee each time you replace the
ads. If you require more control over your ads, we recommend using a mobile ad network such as
<a href='http://www.admob.com' target='_blank'>AdMob</a> or embedding ad code from an Ad Serving platform such as
<a href='http://www.google.com/dfp/' target='_blank'>Google DFP</a>.</p>

</p></div>",
     ));


    $screen->add_help_tab( array(
        'id' => 'using-mopub-advanced',                  //unique id for the tab
        'title' => __('4. Advanced'),                //unique visible title for the tab
        'content' => "<div class='help'><p><h5 class='big'>4. Advanced</h5></p>

<p>This tab contains settings relating to how your app is classified in the Apple App Store.</p>

<p><b>Settings include:</b> Language, Country Availability, Categorization, and Content Classifications.</p>

<p><b>Note:</b> The default settings will be used if you don’t make any changes to this tab (English, All countries,
News category, and No ratings on content).</p>

</div>",
    ) );


    $screen->add_help_tab( array(
        'id' => 'using-mopub-finished',                  //unique id for the tab
        'title' => __('5. Finished!'),            //unique visible title for the tab
        'content' => "<div class='help'><p><h5 class='big'>5. Finished!</h5></p>

        <p>Once you're happy with how your app is configured and displays in the live preview screen, use this tab to
        submit your app configuration to ".$pluginName.".</p>

<p><b>Payment:</b> After clicking the submit button, you'll be taken to the subscription form which you must fill-out.
Once you’ve completed the form, you will be directed to PayPal to complete the payment process.</p>

<p>After your order is finalized, we'll take care of building and publishing your app and will send you an email once
it's live in the App Store. This process typically takes 7-10 working days but this may vary due to factors beyond our
control.</p></div>",
    ) );

}
